### ISSUE TITLE
Adopt semantic versioning for releases

### ISSUE THREAD

**Issue by rom1504** [criteo/cluster-pack#56]
Hi,
I think it would be nice to use semantic versioning for releases versions.
https://semver.org/
It means selecting version numbers as MAJOR.MINOR.PATCH
Major version should be incremented when a breaking change is done
Minor version when a feature is added
Patch when a fix is done
This is very useful for dependents to know how much changes were introduced in a new version.
This works best when major is a version >= 1 so I advise to always start at 1.0.0
Making breaking change is something that is useful to advertise for dependents and increasing the major version definitely make sense in such cases. Being at major version 5 is ok if there was a few refactoring that changed the API a lot.

I believe this versionning scheme is better than the "versionning as marketing" that is adopted by some software which consists in saying "our new major version is a big milestone, look at all the new features" which for dependents is not very useful.

In the case of cluster pack it would be releasing a 1.0.0 then following the scheme when releasing.

What do you think ?

**Comment by fhoering** [comment]
I agree that currently the versions are not very helpful as we always change the patch release.
I think we can do a 1.0.0 soon to indicate that the code can be used now and then respect the MAJOR.MINOR.PATCH scheme for breaking, new features and bugfixes.
