### ISSUE TITLE
Do we need PYTHONPATH to set to spark/python OR do we package pyspark in .pex file?

### ISSUE THREAD

**Issue by vnkesarwani** [criteo/cluster-pack#57]
Hi, I am not able to run the pyspark code until i bundle pyspark in .pex file.

Though in normal scenarios we set PYTHONPATH as below
PYTHONPATH=$SPARK_HOME/python/:$PYTHONPATH
PYTHONPATH=$SPARK_HOME/python/lib/py4j-0.10.7-src.zip:$PYTHONPATH
PYTHONPATH=$SPARK_HOME/python/lib/pyspark.zip:$PYTHONPATH
export PYTHONPATH

spark-submit \
--master yarn \
--deploy-mode cluster \
--conf spark.pyspark.driver.python=./my_application_saprk.pex \
--conf spark.pyspark.python=./my_application_saprk.pex \
--conf spark.executorEnv.PEX_ROOT=./tmp \
--conf spark.yarn.appMasterEnv.PEX_ROOT=./tmp \
--files my_application_saprk.pex \
pyspark_pandas.py

It's not able to find pysaprk

"ModuleNotFoundError: No module named 'pyspark' "

Can any one of you please help here. 

-Thanks

**Comment by fhoering** [comment]
You can do what you do by setting the PYTHONPATH and using SPARK_HOME but the idea of this library is to use the python packages for everything and therefore also using only the python pyspark package.

And in this case you don't need to set the PYTHONPATH manually anymore.

You can just install pyspark into your virtual environment (see https://github.com/criteo/cluster-pack/blob/master/examples/spark-with-S3/scripts/run_spark_example.sh#L7) and then it will be automatically included in the pex file or you include it on your own as you describe.

In our internal code we have SPARK_HOME set on some environments (often with the wrong version). In this case we just unset the env variable (del os.envidon["SPARK_HOME"]) in our python code to get a consistent behavior and always use the pyspark package.
