### ISSUE TITLE
Using pex binary without installing in system

### ISSUE THREAD

**Issue by vnkesarwani** [criteo/cluster-pack#60]
Hi,

1- Is that possible that without installing pex or creating any virtual env, we can use pex command from some binary/package and create pex file?
2- how can we include static files present at some location/Artifactory into pex executable.
3- handling optional packages installed out of virtual env. e.g. NLTK library

**Comment by fhoering** [comment]
1- Is that possible that without installing pex or creating any virtual env, we can use pex command from some binary/package and create pex file?
You need to create a virtual with pex or install pex globally to be able to create it.

2- how can we include static files present at some location/Artifactory into pex executable.
3- handling optional packages installed out of virtual env. e.g. NLTK library
You could create a python wheel and put files/native code inside. But it is hacking around stuff. I guess you are better off with docker.

This lib is really only intended for python packages. If you have complex non python services/dependencies (stuff that is not on pypi, SQL DBs, ..) you should use something else.
