### ISSUE TITLE
Inconsistent kernel environment uploaded in jupyter notebook

### ISSUE THREAD

**Issue by darkjh** [criteo/cluster-pack#74]
Hi, 

We use cluster-pack in jupyter notebooks with conda environments. 
An issue we've found is that when the kernel is in a different conda environment than the jupter notebook server, the uploaded zip (`env_name.tar.gz`) contains the envionrment of jupyter notebook but the description file `env_name.tar.json` list the correct kernel environment.

A concrete example:
1. `jupyter notebook` installed and launched from `jupyter` conda env
2. Another conda env `tf` is created and its kernel is installed
3. Launch a notebook using the `tf` kernel
4. Do `package_path, _ = cluster_pack.upload_env()`
5. `jupyter.tar.json` and `jupyter.tar.gz` are uploaded
6. `jupyter.tar.json` lists correctly the libs in `tf` conda env (not `jupyter`)
7. But `jupyter.tar.gz` packages actually the `jupyter` conda env

**Comment by fhoering** [comment]
Hello,

We also use this with jupyter but with virtual environments kernel or pex kernels. I will check if I can reproduce this in a conda env.

**Comment by darkjh** [comment]
@fhoering 
It seems conda-pack will just pack the default env (not kernel's) https://github.com/criteo/cluster-pack/blob/master/cluster_pack/conda.py#L91
However the metadata is generated here https://github.com/criteo/cluster-pack/blob/master/cluster_pack/packaging.py#L281 
And it looks at the `sys.executable` which will correctly point at the kernel's executable.

**Comment by darkjh** [comment]
@fhoering 
Seems https://github.com/darkjh/cluster-pack/commit/ed8dd55ff6a4324d21320f9788c01ade986ba658 fix the problem on our jupyter setup with conda.
If this approach is ok for you, I can open a pull request.

**Comment by fhoering** [comment]
OK. If it also works when we just have a current conda venv it look good. You can submit a PR if you want.
There are also some tests for conda here:
https://github.com/criteo/cluster-pack/blob/master/tests/test_conda.py
It looks complicated to setup a jupyter kernel in a test but if it just works with those test it is good enough.
